#ifndef OPYCHAMFERGEN_H_
#define OPYCHAMFERGEN_H_

enum
{
	ID_CHAMFERGEN_SELECTIONANGLE = 1000,
	ID_CHAMFERGEN_INPUTLINK = 1001,
	ID_CHAMFERGEN_SPLINETYPE = 1002,
		ID_CHAMFERGEN_LINEAR = 0,
		ID_CHAMFERGEN_AKIMA = 1,
	ID_CHAMFERGEN_BSPLINE = 2,
	ID_CHAMFERGEN_SUBDIVISIONS = 1003,
	ID_CHAMFERGEN_OVERRIDETYPE = 1004,
	ID_CHAMFERGEN_FLAT = 1005,
	ID_CHAMFERGEN_RADIUS = 1006,
	ID_CHAMFERGEN_OPTIMIZEANGLE = 1007,
	ID_CHAMFERGEN_POINTSELECTION = 1008,
	ID_CHAMFERGEN_MODE = 1009,
		ID_CHAMFERGEN_CHAMFER = 0,
		ID_CHAMFERGEN_OFFSET = 1,
	ID_CHAMFERGEN_DISTANCE = 1010
};

#endif // OPYCHAMFERGEN_H_