CONTAINER opychamfergen
{
	NAME opychamfergen;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG ID_CHAMFERGEN_MODE
		{
			CYCLE
			{
				ID_CHAMFERGEN_CHAMFER;
				ID_CHAMFERGEN_OFFSET;
			}
		}
		LINK ID_CHAMFERGEN_INPUTLINK {}
		SEPARATOR { LINE; }
		// chamfer settings
		STRING ID_CHAMFERGEN_POINTSELECTION { }
		REAL ID_CHAMFERGEN_SELECTIONANGLE { UNIT DEGREE; MIN 0.0; MAX 180;}
		BOOL ID_CHAMFERGEN_FLAT {}
		REAL ID_CHAMFERGEN_RADIUS { UNIT METER; MIN 0.0; }
		// offset settings
		REAL ID_CHAMFERGEN_DISTANCE { UNIT METER; }
		SEPARATOR { LINE; }
		REAL ID_CHAMFERGEN_OPTIMIZEANGLE { UNIT DEGREE; MIN 0.0; MAX 180; }
		SEPARATOR { LINE; }
		BOOL ID_CHAMFERGEN_OVERRIDETYPE {}
		LONG ID_CHAMFERGEN_SPLINETYPE
		{
			CYCLE
			{
				ID_CHAMFERGEN_LINEAR;
				ID_CHAMFERGEN_AKIMA;
				ID_CHAMFERGEN_BSPLINE;
			}
		}
		LONG ID_CHAMFERGEN_SUBDIVISIONS { MIN 0; }

	}
}
